#!/bin/sh
CONF=/etc/config/qpkg.conf
QPKG_NAME="pdulvp-nas-standby"
INSTALL_PATH=`/sbin/getcfg -f $CONF $QPKG_NAME Install_Path`

# iff invoked inside CHROOT environment
[ -z "$CHROOT_DIR" -o -z "$QPKG_CLASS" ] && exit 1

echo "Start rcK_$QPKG_NAME.sh" 					>>/tmp/$QPKG_NAME.log

#killall pdulvp-nas-standby
[ -f /tmp/${QPKG_CLASS}-${QPKG_NAME}.pid ] && kill $(cat /tmp/${QPKG_CLASS}-${QPKG_NAME}.pid) && sleep 1

[ -L "/opt/${QPKG_NAME}/sys-power-state" ] && rm -f "/opt/${QPKG_NAME}/sys-power-state"
[ -L "/opt/startup_shell/startup_${QPKG_NAME}.sh" ] && rm -f "/opt/startup_shell/startup_${QPKG_NAME}.sh"
[ -L "/opt/startup_shell/stop_${QPKG_NAME}.sh" ] && rm -f "/opt/startup_shell/stop_${QPKG_NAME}.sh"
